name: Build and Deploy My App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  IMAGE: jl115/(App Name):${{ github.sha }}
  CONFIG_PATH: ./k8s
  KUBERNETES_NAMESPACE: (k8s-namespace) # Replace with your actual Kubernetes namespace
  APP_NAME: (App Name) # Replace with your actual app name
  BASE_URL: joelleimbacher.tech
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build-and-deploy:
    # Only run on merged pull request
    if: github.event_name == 'pull_request' && github.event.pull_request.merged == true
    runs-on: self-hosted
    name: Build and Deploy to Kubernetes

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE }}

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: "latest"

      - name: Write kubeconfig file
        run: |
          echo "${{ secrets.KUBECONFIG }}" | base64 --decode > kubeconfig
          chmod 600 kubeconfig
      - name: Replace and Apply Kubernetes Manifests
        uses: swdotcom/update-and-apply-kubernetes-configs@v1
        with:
          k8-config-file-paths: |
            ./k8s/namespace.yaml
            ./k8s/envs.yaml
            ./k8s/deploy.yaml
            ./k8s/service.yaml
            ./k8s/ingress.yaml
          replacement-method: defined
        env:
          KUBECONFIG: kubeconfig
